In [32]:
# imports

from filterpy.kalman import KalmanFilter
from filterpy.kalman import predict
from filterpy.kalman import KalmanFilter
from filterpy.common import Q_discrete_white_noise

import numpy as np 
import csv 
import matplotlib.pyplot as plt 
import pandas as pd 

In [16]:
# data

fpath = "maybe_cleaned_sleep_analysis.csv"
df = pd.read_csv(fpath)

sleep_data = [row for row in df["value"]]
S = np.array(sleep_data)

In [ ]:
# interpolate

In [35]:
# filter

kf = KalmanFilter(dim_x=2, dim_z=1)
kf.x = np.array([2., 0.])
kf.F = np.array([[1.,1.],
                 [0.,1.]])
kf.H = np.array([[1.,0.]])
kf.P = np.array([[1000.,    0.],
                 [   0., 1000.]])
kf.R = np.array([[5.]])
kf.Q = Q_discrete_white_noise(dim=2, dt=0.1, var=0.13)

In [36]:
# use filter

interpolated = list()
dates = list()

with open("interpolated_sleep_analysis.csv", 'r') as f:
    reader = csv.reader(f)
    next(reader)
    for row in reader:
        interpolated.append(float(row[1]))
        dates.append(pd.to_datetime(row[0]))

S = iter(interpolated)

z = next(S, None)
while z is not None:

    kf.predict()
    kf.update(z)

    z = next(S, None)

In [39]:
kf.x

array([0.23135223, 0.01984274])

In [40]:
kf.x_post

array([0.23135223, 0.01984274])

In [41]:
kf.x_prior

array([0.11943218, 0.00981174])